name: Checkmarx-Pull-Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
jobs:
  # This workflow contains a single job called "build"
  Checkmarx-Analysis:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Code Checkout
      uses: actions/checkout@v2
    - run: set
    - name: Checkmarx Scan
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.4
      with:
        project: PR-simply_vulnerable_react-${{ github.head_ref }}
        team: /CxServer/GitHubAction
        checkmarx_url: ${{ secrets.CHECKMARX_URL }}
        checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
        checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
        checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
        scanners: sast
        incremental: false
        break_build: true
        bug_tracker: GITHUBPULL
        preset: Checkmarx Express
        params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} --merge-id=${{ github.event.number }} --checkmarx.cx-branch=true --github.block-merge=true
        
